user:
  owner    : <user-name>
  owner_id : <user-id>
secrets:
  access_token    : <access-token>
  access_secret   : <access-secret>
  consumer_key    : <consumer-key>
  consumer_secret : <consumer-secret>
search:
  languages:
    - en
    - es
  track:
    - 😂
